using FitTracker.Api.DTOs;
using FitTracker.Api.Models;

namespace FitTracker.Api.Repositories.Interfaces;

public interface IChatRepository
{
    /// <summary>
    /// Persists a new chat message, or returns the existing one when this id has
    /// already been stored for the same pair.
    /// </summary>
    /// <remarks>
    /// The id is generated by the sending client, not here. That is what makes a
    /// resend safe: a client that never received an ack cannot tell whether the
    /// original insert landed, so it always resends, and this method decides.
    /// </remarks>
    /// <exception cref="InvalidOperationException">
    /// The id already exists against a different trainer-client pair.
    /// </exception>
    Task<ChatMessage> AddMessageAsync(ChatMessage chatMessage);

    /// <summary>Returns up to <paramref name="range"/> of the most recent messages between the trainer and client, oldest first.</summary>
    Task<List<ChatMessage>> GetChatHistoryAsync(Guid trainerId, Guid client, int range);

    /// <summary>
    /// Every Active thread <paramref name="userId"/> is a party to, with the last
    /// message and the caller's own unread count.
    /// </summary>
    Task<List<ChatConversationDto>> GetConversationsAsync(Guid userId);

    /// <summary>
    /// Stamps <paramref name="userId"/>'s side of their thread with
    /// <paramref name="otherPartyId"/> as read. Returns false when no Active
    /// relationship joins the two.
    /// </summary>
    Task<bool> MarkReadAsync(Guid userId, Guid otherPartyId, DateTime readAt);
}
