import 'package:drift/drift.dart' as drift;
import 'package:ForgeForm/core/app_database.dart';
import 'package:ForgeForm/feature/workout_planning/data/models/exercise.dart';

Future<void> seedExercisesIfEmpty(AppDatabase db) async {
  final existingExercises = await db.exerciseDao.getAllExercises();
  if (existingExercises.isEmpty) {
    await _insertAll(db);
  } else {
    // Backfill German translations for exercises seeded before this feature.
    await _backfillTranslations(db);
  }
}

Future<void> _insertAll(AppDatabase db) async {
  for (final exercise in _exercises) {
    await db.exerciseDao.saveExercise(db.exerciseDao.modelToEntity(exercise));
  }
}

/// Updates any pre-existing exercise that still has a null nameDe,
/// matched by English name. Custom exercises are never touched.
Future<void> _backfillTranslations(AppDatabase db) async {
  final all = await db.exerciseDao.getAllExercises();
  final needsUpdate = all.where((e) => e.nameDe == null && !e.isCustom);
  if (needsUpdate.isEmpty) return;

  final translationMap = {
    for (final ex in _exercises)
      if (ex.nameDe != null)
        ex.name: (nameDe: ex.nameDe!, descriptionDe: ex.descriptionDe),
  };

  for (final row in needsUpdate) {
    final t = translationMap[row.name];
    if (t == null) continue;
    await (db.update(db.exerciseTable)..where((e) => e.id.equals(row.id)))
        .write(ExerciseTableCompanion(
      nameDe: drift.Value(t.nameDe),
      descriptionDe: drift.Value(t.descriptionDe),
    ));
  }
}

final _exercises = <Exercise>[
  // ── CHEST (21) ────────────────────────────────────────────────────────────
  Exercise(
    name: 'Barbell Bench Press',
    nameDe: 'Langhantel Bankdrücken',
    description: 'Lie on a flat bench and press the barbell from chest to full arm extension.',
    descriptionDe: 'Auf einer flachen Bank liegen und die Langhantel von der Brust bis zur vollen Armstreckung drücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Incline Barbell Bench Press',
    nameDe: 'Schrägbankdrücken mit Langhantel',
    description: 'Bench press performed on an incline bench to target upper chest.',
    descriptionDe: 'Bankdrücken auf einer Schrägbank zur Aktivierung des oberen Brustmuskels.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Incline Barbell Bench Press(Smith Machine)',
    nameDe: 'Schrägbankdrücken (Smith Machine)',
    description: 'Bench press performed on an incline bench to target upper chest.',
    descriptionDe: 'Schrägbankdrücken an der Smith Machine zur Aktivierung des oberen Brustmuskels.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Decline Barbell Bench Press',
    nameDe: 'Negatives Bankdrücken mit Langhantel',
    description: 'Bench press on a decline bench targeting lower chest.',
    descriptionDe: 'Bankdrücken auf einer negativen Bank zur Aktivierung des unteren Brustmuskels.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Bench Press',
    nameDe: 'Kurzhantelbankdrücken',
    description: 'Press dumbbells from chest level while lying on a flat bench.',
    descriptionDe: 'Kurzhanteln von der Brust drücken, liegend auf einer flachen Bank.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Incline Dumbbell Press',
    nameDe: 'Schrägbankdrücken mit Kurzhantel',
    description: 'Dumbbell press on an incline bench for upper chest development.',
    descriptionDe: 'Kurzhanteldrücken auf einer Schrägbank für die Oberbrust.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Decline Dumbbell Press',
    nameDe: 'Negatives Kurzhantelbankdrücken',
    description: 'Dumbbell press on a decline bench targeting lower chest.',
    descriptionDe: 'Kurzhanteldrücken auf einer negativen Bank für die Unterbrust.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Flyes',
    nameDe: 'Kurzhantel Fliegende',
    description: 'Lying dumbbell flyes with arms in arc motion to stretch and contract chest.',
    descriptionDe: 'Liegende Kurzhantel-Fliegende mit Bogenbewegung zur Dehnung und Kontraktion der Brust.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Incline Dumbbell Flyes',
    nameDe: 'Schrägbank Kurzhantel Fliegende',
    description: 'Flyes performed on incline bench for upper chest isolation.',
    descriptionDe: 'Fliegende auf der Schrägbank zur Isolation des oberen Brustmuskels.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Cable Crossover',
    nameDe: 'Kabelzug Crossover',
    description: 'Stand between cable pulleys and bring handles together in front of chest.',
    descriptionDe: 'Zwischen zwei Kabelzügen stehen und die Griffe vor der Brust zusammenführen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Low Cable Crossover',
    nameDe: 'Tiefer Kabelzug Crossover',
    description: 'Cable crossover from low position targeting upper chest.',
    descriptionDe: 'Kabelzug-Crossover von unten für den oberen Brustmuskel.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Push-Ups',
    nameDe: 'Liegestütze',
    description: 'Classic bodyweight exercise pushing body up from prone position.',
    descriptionDe: 'Klassische Körpergewichtsübung: Körper aus der Bauchlage nach oben drücken.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Decline Push-Ups',
    nameDe: 'Erhöhte Liegestütze',
    description: 'Push-ups with feet elevated to increase difficulty.',
    descriptionDe: 'Liegestütze mit erhöhten Füßen für mehr Schwierigkeit.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Dips (Chest)',
    nameDe: 'Dips (Brust)',
    description: 'Lean forward on parallel bars and dip down to target chest.',
    descriptionDe: 'An Parallelstangen nach vorne lehnen und absenken, um die Brust zu belasten.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Cable Flyes',
    nameDe: 'Kabelzug Fliegende',
    description: 'Cable flyes from mid-height for chest isolation.',
    descriptionDe: 'Kabelzug-Fliegende auf mittlerer Höhe zur Brustmuskel-Isolation.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Pec Deck Machine',
    nameDe: 'Butterfly Maschine',
    description: 'Machine-based fly movement for chest isolation.',
    descriptionDe: 'Maschinenbasierte Butterfly-Bewegung zur Brustmuskel-Isolation.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Chest Press Machine',
    nameDe: 'Brustpresse Maschine',
    description: 'Machine press for controlled chest development.',
    descriptionDe: 'Maschinendrücken für kontrollierten Brustmuskelaufbau.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Incline Cable Flyes',
    nameDe: 'Schrägbank Kabelzug Fliegende',
    description: 'Cable flyes from low position for upper chest.',
    descriptionDe: 'Kabelzug-Fliegende von unten für die Oberbrust.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Close-Grip Bench Press',
    nameDe: 'Enges Bankdrücken',
    description: 'Bench press with narrow grip emphasizing inner chest and triceps.',
    descriptionDe: 'Bankdrücken mit engem Griff für die innere Brust und den Trizeps.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest, MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Wide-Grip Bench Press',
    nameDe: 'Weites Bankdrücken',
    description: 'Bench press with wide grip for outer chest emphasis.',
    descriptionDe: 'Bankdrücken mit weitem Griff für den äußeren Brustmuskel.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Smith Machine Bench Press',
    nameDe: 'Smith Machine Bankdrücken',
    description: 'Guided bench press using Smith machine for stability.',
    descriptionDe: 'Geführtes Bankdrücken an der Smith Machine für mehr Stabilität.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.chest],
    isCustom: false,
  ),

  // ── BACK (26) ─────────────────────────────────────────────────────────────
  Exercise(
    name: 'Barbell Deadlift',
    nameDe: 'Langhantel Kreuzheben',
    description: 'Lift barbell from floor to standing position with straight back.',
    descriptionDe: 'Langhantel mit geradem Rücken vom Boden in den Stand heben.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back, MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Romanian Deadlift',
    nameDe: 'Rumänisches Kreuzheben',
    description: 'Deadlift variation with slight knee bend emphasizing hamstrings and lower back.',
    descriptionDe: 'Kreuzheben-Variante mit leicht gebeugten Knien für Oberschenkelrückseite und unteren Rücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back, MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Sumo Deadlift',
    nameDe: 'Sumo Kreuzheben',
    description: 'Deadlift with wide stance and toes pointed out.',
    descriptionDe: 'Kreuzheben mit breitem Stand und nach außen gedrehten Zehen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back, MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Bent Over Barbell Row',
    nameDe: 'Vorgebeugtes Langhantelrudern',
    description: 'Bent forward, row barbell to lower chest with elbows close.',
    descriptionDe: 'Vorgebeugt die Langhantel zur unteren Brust ziehen, Ellbogen nah am Körper.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'T-Bar Row',
    nameDe: 'T-Stangenrudern',
    description: 'Row using landmine barbell setup for thick back development.',
    descriptionDe: 'Rudern mit festgeklemmter Langhantel für einen breiten Rücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Pendlay Row',
    nameDe: 'Pendlay Rudern',
    description: 'Explosive barbell row from floor with torso parallel to ground.',
    descriptionDe: 'Explosives Langhantelrudern vom Boden mit waagerechtem Oberkörper.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Pull-Ups',
    nameDe: 'Klimmzüge',
    description: 'Pull body up to bar with palms facing away.',
    descriptionDe: 'Körper zur Stange hochziehen, Handflächen zeigen nach vorne.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Chin-Ups',
    nameDe: 'Untergriff Klimmzüge',
    description: 'Pull body up to bar with palms facing toward you.',
    descriptionDe: 'Körper zur Stange hochziehen, Handflächen zeigen zur Person.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.back, MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Lat Pulldown',
    nameDe: 'Latzug',
    description: 'Pull cable bar down to upper chest while seated.',
    descriptionDe: 'Kabelstange im Sitzen zur Oberbrust herunterziehen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Wide-Grip Lat Pulldown',
    nameDe: 'Latzug weiter Griff',
    description: 'Lat pulldown with wide grip for lat width.',
    descriptionDe: 'Latzug mit weitem Griff für die Latissimusbreite.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Close-Grip Lat Pulldown',
    nameDe: 'Latzug enger Griff',
    description: 'Lat pulldown with close grip for lat thickness.',
    descriptionDe: 'Latzug mit engem Griff für die Latissimusdicke.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Seated Cable Row',
    nameDe: 'Sitzrudern am Kabel',
    description: 'Pull cable handle to torso while seated with legs extended.',
    descriptionDe: 'Kabelgriff im Sitzen mit ausgestreckten Beinen zum Körper ziehen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'One-Arm Dumbbell Row',
    nameDe: 'Einarmiges Kurzhantelrudern',
    description: 'Row dumbbell to hip with one hand while braced on bench.',
    descriptionDe: 'Kurzhantel mit einer Hand zur Hüfte ziehen, andere Hand auf der Bank abstützen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Row',
    nameDe: 'Kurzhantelrudern',
    description: 'Bent over row with both dumbbells simultaneously.',
    descriptionDe: 'Vorgebeugtes Rudern mit beiden Kurzhanteln gleichzeitig.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Barbell Shrug',
    nameDe: 'Langhantel Schulternzucken',
    description: 'Shrug shoulders up while holding barbell to work traps.',
    descriptionDe: 'Schultern mit Langhantel nach oben ziehen für den Trapezmuskel.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Kelso Shrugs',
    nameDe: 'Kelso Schulternzucken',
    description: 'Lean forward slightly and shrug the shoulders back and up to target the mid-traps and rhomboids.',
    descriptionDe: 'Leicht vorbeugen und Schultern nach hinten oben ziehen für mittleren Trapez und Rhomboiden.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Shrug',
    nameDe: 'Kurzhantel Schulternzucken',
    description: 'Shrug shoulders with dumbbells for trap development.',
    descriptionDe: 'Schultern mit Kurzhanteln hochziehen für den Trapezmuskel.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Face Pulls',
    nameDe: 'Gesichtszug',
    description: 'Pull rope to face level for rear delts and upper back.',
    descriptionDe: 'Seil auf Gesichtshöhe ziehen für hintere Schulter und oberen Rücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back, MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Straight-Arm Pulldown',
    nameDe: 'Latzug gestreckter Arm',
    description: 'Push bar down with straight arms to isolate lats.',
    descriptionDe: 'Stange mit gestreckten Armen nach unten drücken zur Latissimus-Isolation.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Machine Row',
    nameDe: 'Maschinenrudern',
    description: 'Rowing movement on machine for controlled back work.',
    descriptionDe: 'Ruderbewegung an der Maschine für kontrollierten Rückenaufbau.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Inverted Row',
    nameDe: 'Australische Klimmzüge',
    description: 'Bodyweight row under bar or table.',
    descriptionDe: 'Körpergewichtsrudern unter einer Stange oder einem Tisch.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Hyperextensions',
    nameDe: 'Rückenstrecker',
    description: 'Extend torso on hyperextension bench for lower back.',
    descriptionDe: 'Oberkörper auf dem Rückenstrecker-Gerät strecken für den unteren Rücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Good Mornings',
    nameDe: 'Guten Morgen Übung',
    description: 'Bend forward at hips with barbell on back.',
    descriptionDe: 'Mit Langhantel auf dem Rücken an der Hüfte vorbeugen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back, MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Rack Pulls',
    nameDe: 'Rack Zug',
    description: 'Deadlift from elevated position for upper back emphasis.',
    descriptionDe: 'Kreuzheben aus erhöhter Position für den oberen Rücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Cable Shrugs',
    nameDe: 'Kabelzug Schulternzucken',
    description: 'Shrug movement using cable for constant tension.',
    descriptionDe: 'Schulternzucken am Kabelzug für konstante Spannung.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back],
    isCustom: false,
  ),
  Exercise(
    name: 'Rope Face Pulls',
    nameDe: 'Seil Gesichtszug',
    description: 'Face pulls with rope attachment for rear delts.',
    descriptionDe: 'Gesichtszug mit Seilaufsatz für die hintere Schulter.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.back, MuscleGroup.shoulders],
    isCustom: false,
  ),

  // ── SHOULDERS (18) ────────────────────────────────────────────────────────
  Exercise(
    name: 'Overhead Press',
    nameDe: 'Überkopfdrücken',
    description: 'Press barbell from shoulders to overhead lockout.',
    descriptionDe: 'Langhantel von den Schultern bis zur vollen Streckung über den Kopf drücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Military Press',
    nameDe: 'Militärpresse',
    description: 'Strict overhead press with feet together.',
    descriptionDe: 'Striktes Überkopfdrücken mit geschlossenen Füßen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Shoulder Press',
    nameDe: 'Kurzhantel Schulterdrücken',
    description: 'Press dumbbells overhead while seated or standing.',
    descriptionDe: 'Kurzhanteln im Sitzen oder Stehen über den Kopf drücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Arnold Press',
    nameDe: 'Arnold Press',
    description: 'Dumbbell press with rotation from palms-in to palms-out.',
    descriptionDe: 'Kurzhanteldrücken mit Rotation von Handflächen innen zu außen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Seated Dumbbell Press',
    nameDe: 'Sitzendes Kurzhantel Schulterdrücken',
    description: 'Seated variation of dumbbell overhead press.',
    descriptionDe: 'Sitzende Variante des Kurzhantel-Überkopfdrückens.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Lateral Raises',
    nameDe: 'Seitheben',
    description: 'Raise arms to sides for side delt development.',
    descriptionDe: 'Arme seitlich heben für den seitlichen Deltamuskel.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Lateral Raises',
    nameDe: 'Kurzhantel Seitheben',
    description: 'Raise dumbbells out to sides to shoulder height.',
    descriptionDe: 'Kurzhanteln seitlich auf Schulterhöhe heben.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Cable Lateral Raises',
    nameDe: 'Kabelzug Seitheben',
    description: 'Lateral raises using cable for constant tension.',
    descriptionDe: 'Seitheben am Kabelzug für konstante Spannung.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Front Raises',
    nameDe: 'Frontheben',
    description: 'Raise weight in front of body to shoulder height.',
    descriptionDe: 'Gewicht vor dem Körper auf Schulterhöhe heben.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Barbell Front Raises',
    nameDe: 'Langhantel Frontheben',
    description: 'Front raises holding barbell with both hands.',
    descriptionDe: 'Frontheben mit der Langhantel beidhändig.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Rear Delt Flyes',
    nameDe: 'Hintere Schulter Fliegende',
    description: 'Bent over flyes for rear deltoid isolation.',
    descriptionDe: 'Vorgebeugtes Fliegende für die Isolation der hinteren Schulter.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Reverse Pec Deck',
    nameDe: 'Umgekehrtes Butterfly',
    description: 'Machine fly for rear delts with chest against pad.',
    descriptionDe: 'Maschinen-Fliegende für hintere Schulter, Brust an der Polsterung.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Upright Row',
    nameDe: 'Hochziehen',
    description: 'Pull bar up along torso to shoulder height.',
    descriptionDe: 'Stange am Körper entlang auf Schulterhöhe hochziehen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Bradford Press',
    nameDe: 'Bradford Press',
    description: 'Alternate pressing in front and behind head.',
    descriptionDe: 'Abwechselnd vor und hinter dem Kopf drücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Push Press',
    nameDe: 'Stoßdrücken',
    description: 'Overhead press with leg drive for momentum.',
    descriptionDe: 'Überkopfdrücken mit Beinschwung für mehr Schwungkraft.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Machine Shoulder Press',
    nameDe: 'Schulterdrücken Maschine',
    description: 'Guided overhead press on machine.',
    descriptionDe: 'Geführtes Überkopfdrücken an der Maschine.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Cable Front Raises',
    nameDe: 'Kabelzug Frontheben',
    description: 'Front raises using cable for constant tension.',
    descriptionDe: 'Frontheben am Kabelzug für konstante Spannung.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),
  Exercise(
    name: 'Seated Lateral Raises',
    nameDe: 'Sitzendes Seitheben',
    description: 'Lateral raises performed while seated for strict form.',
    descriptionDe: 'Seitheben im Sitzen für saubere Ausführung.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.shoulders],
    isCustom: false,
  ),

  // ── BICEPS (12) ───────────────────────────────────────────────────────────
  Exercise(
    name: 'Barbell Curl',
    nameDe: 'Langhantel Bizepscurl',
    description: 'Curl barbell from thighs to shoulders with supinated grip.',
    descriptionDe: 'Langhantel mit Untergriff von den Oberschenkeln zu den Schultern curlen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'EZ-Bar Curl',
    nameDe: 'EZ-Stange Curl',
    description: 'Curl EZ-bar to reduce wrist strain.',
    descriptionDe: 'EZ-Stange curlen zur Entlastung der Handgelenke.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Curl',
    nameDe: 'Kurzhantel Bizepscurl',
    description: 'Alternating or simultaneous dumbbell curls.',
    descriptionDe: 'Abwechselnde oder gleichzeitige Kurzhantel-Curls.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Hammer Curl',
    nameDe: 'Hammercurl',
    description: 'Curl dumbbells with neutral grip (palms facing each other).',
    descriptionDe: 'Kurzhanteln mit neutralem Griff curlen (Handflächen zueinander).',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Preacher Curl',
    nameDe: 'Scottcurl',
    description: 'Curl on preacher bench for strict bicep isolation.',
    descriptionDe: 'Curl auf der Scottbank für strikte Bizeps-Isolation.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Concentration Curl',
    nameDe: 'Konzentrationscurl',
    description: 'Single-arm curl seated with elbow braced on inner thigh.',
    descriptionDe: 'Einarmiger Curl im Sitzen, Ellbogen am Innenschenkel abgestützt.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Cable Curl',
    nameDe: 'Kabelzug Bizepscurl',
    description: 'Bicep curl using cable machine for constant tension.',
    descriptionDe: 'Bizepscurl am Kabelzug für konstante Spannung.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Incline Dumbbell Curl',
    nameDe: 'Schrägbank Kurzhantel Curl',
    description: 'Curl on incline bench for full bicep stretch.',
    descriptionDe: 'Curl auf der Schrägbank für vollständige Bizepsdehnung.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Spider Curl',
    nameDe: 'Spider Curl',
    description: 'Curl over incline bench with chest against pad.',
    descriptionDe: 'Curl über die Schrägbank, Brust an der Polsterung.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Reverse Curl',
    nameDe: 'Umgekehrter Curl',
    description: 'Curl with pronated grip to work forearms and biceps.',
    descriptionDe: 'Curl mit Übergriff für Unterarme und Bizeps.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Cable Hammer Curl',
    nameDe: 'Kabelzug Hammercurl',
    description: 'Hammer curls using rope attachment on cable.',
    descriptionDe: 'Hammercurls mit Seilaufsatz am Kabelzug.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),
  Exercise(
    name: '21s',
    nameDe: '21er Curls',
    description: 'Barbell curl variation: 7 bottom half, 7 top half, 7 full range.',
    descriptionDe: 'Langhantel-Curl-Variation: 7 untere Hälfte, 7 obere Hälfte, 7 voller Bewegungsumfang.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.biceps],
    isCustom: false,
  ),

  // ── TRICEPS (12) ──────────────────────────────────────────────────────────
  Exercise(
    name: 'Tricep Dips',
    nameDe: 'Trizeps Dips',
    description: 'Dip between parallel bars keeping torso upright.',
    descriptionDe: 'An Parallelstangen absenken mit aufrechtem Oberkörper.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Close-Grip Bench Press',
    nameDe: 'Enges Bankdrücken',
    description: 'Bench press with hands close together for tricep emphasis.',
    descriptionDe: 'Bankdrücken mit eng beieinanderliegenden Händen für den Trizeps.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.triceps, MuscleGroup.chest],
    isCustom: false,
  ),
  Exercise(
    name: 'Skull Crushers',
    nameDe: 'Stirndrücken',
    description: 'Lower bar to forehead and extend arms while lying down.',
    descriptionDe: 'Stange liegend zur Stirn senken und Arme strecken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'EZ-Bar Skull Crushers',
    nameDe: 'EZ-Stange Stirndrücken',
    description: 'Skull crushers using EZ-bar for wrist comfort.',
    descriptionDe: 'Stirndrücken mit EZ-Stange für mehr Handgelenkkomfort.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Overhead Tricep Extension',
    nameDe: 'Trizeps Überkopfstrecken',
    description: 'Extend weight overhead from behind head.',
    descriptionDe: 'Gewicht hinter dem Kopf nach oben strecken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Overhead Extension',
    nameDe: 'Kurzhantel Überkopfstrecken',
    description: 'Single dumbbell held with both hands extended overhead.',
    descriptionDe: 'Eine Kurzhantel beidhändig über den Kopf strecken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Cable Pushdown',
    nameDe: 'Kabelzug Trizepsdrücken',
    description: 'Push cable bar down by extending elbows.',
    descriptionDe: 'Kabelstange durch Strecken der Ellbogen nach unten drücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Rope Pushdown',
    nameDe: 'Seil Trizepsdrücken',
    description: 'Cable pushdown with rope for full tricep contraction.',
    descriptionDe: 'Kabeldrücken mit Seil für vollständige Trizepskontraktion.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Tricep Kickbacks',
    nameDe: 'Trizeps Rückwärtsstrecken',
    description: 'Bent over, extend arm back fully to work triceps.',
    descriptionDe: 'Vorgebeugt den Arm vollständig nach hinten strecken für den Trizeps.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Kickbacks',
    nameDe: 'Kurzhantel Rückwärtsstrecken',
    description: 'Single-arm kickbacks using dumbbells.',
    descriptionDe: 'Einarmiges Rückwärtsstrecken mit Kurzhantel.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Diamond Push-Ups',
    nameDe: 'Diamant Liegestütze',
    description: 'Push-ups with hands forming diamond shape.',
    descriptionDe: 'Liegestütze mit Händen in Diamantform.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),
  Exercise(
    name: 'Bench Dips',
    nameDe: 'Bank Dips',
    description: 'Dips using bench with feet on ground or elevated.',
    descriptionDe: 'Dips an der Bank mit Füßen auf dem Boden oder erhöht.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.triceps],
    isCustom: false,
  ),

  // ── LEGS (34) ─────────────────────────────────────────────────────────────
  Exercise(
    name: 'Barbell Squat',
    nameDe: 'Langhantel Kniebeuge',
    description: 'Squat with barbell on back to parallel or below.',
    descriptionDe: 'Kniebeuge mit Langhantel auf dem Rücken bis zur Parallelen oder tiefer.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Front Squat',
    nameDe: 'Frontkniebeuge',
    description: 'Squat with barbell held on front of shoulders.',
    descriptionDe: 'Kniebeuge mit Langhantel an der Vorderseite der Schultern.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Goblet Squat',
    nameDe: 'Goblet Kniebeuge',
    description: 'Squat holding dumbbell or kettlebell at chest.',
    descriptionDe: 'Kniebeuge mit Kurzhantel oder Kettlebell vor der Brust.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Bulgarian Split Squat',
    nameDe: 'Bulgarische Kniebeuge',
    description: 'Single-leg squat with rear foot elevated.',
    descriptionDe: 'Einbeinige Kniebeuge mit erhöhtem hinterem Fuß.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Leg Press',
    nameDe: 'Beinpresse',
    description: 'Press weight platform away with legs.',
    descriptionDe: 'Gewichtsplatte mit den Beinen wegdrücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Hack Squat',
    nameDe: 'Hack Kniebeuge',
    description: 'Squat on machine with back against pad.',
    descriptionDe: 'Kniebeuge an der Maschine mit Rücken an der Polsterung.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Stiff-Leg Deadlift',
    nameDe: 'Gestrecktes Kreuzheben',
    description: 'Deadlift with straight legs for hamstring emphasis.',
    descriptionDe: 'Kreuzheben mit gestreckten Beinen für die Oberschenkelrückseite.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Walking Lunges',
    nameDe: 'Gehende Ausfallschritte',
    description: 'Lunge forward alternating legs while walking.',
    descriptionDe: 'Ausfallschritte vorwärts mit abwechselnden Beinen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Reverse Lunges',
    nameDe: 'Rückwärtige Ausfallschritte',
    description: 'Step backward into lunge position.',
    descriptionDe: 'Rückwärts in die Ausfallschrittposition treten.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Forward Lunges',
    nameDe: 'Vorwärtige Ausfallschritte',
    description: 'Step forward into lunge and return to start.',
    descriptionDe: 'Vorwärts in den Ausfallschritt treten und zurückkehren.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Lying Leg Curls',
    nameDe: 'Liegende Beincurls',
    description: 'Curl legs up on machine while lying face down.',
    descriptionDe: 'Beine auf der Maschine bäuchlings nach oben curlen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Seated Leg Curls',
    nameDe: 'Sitzende Beincurls',
    description: 'Leg curl performed in seated position.',
    descriptionDe: 'Beincurl im Sitzen ausgeführt.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Leg Extensions',
    nameDe: 'Beinstrecker',
    description: 'Extend legs on machine to work quadriceps.',
    descriptionDe: 'Beine an der Maschine strecken für den Quadrizeps.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Leg Press Calf Raise',
    nameDe: 'Beinpresse Wadenheben',
    description: 'Calf raises performed on leg press machine.',
    descriptionDe: 'Wadenheben an der Beinpressmaschine.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Standing Calf Raises',
    nameDe: 'Stehende Wadenheber',
    description: 'Raise up on toes on calf machine while standing.',
    descriptionDe: 'Im Stehen auf Zehenspitzen heben an der Wadenmaschine.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Seated Calf Raises',
    nameDe: 'Sitzende Wadenheber',
    description: 'Calf raises performed seated with weight on knees.',
    descriptionDe: 'Wadenheben im Sitzen mit Gewicht auf den Knien.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Donkey Calf Raises',
    nameDe: 'Esel Wadenheber',
    description: 'Calf raises bent over with weight on lower back.',
    descriptionDe: 'Wadenheben vorgebeugt mit Gewicht auf dem unteren Rücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Box Jumps',
    nameDe: 'Kastensprünge',
    description: 'Jump explosively onto elevated box or platform.',
    descriptionDe: 'Explosiv auf eine erhöhte Kiste oder Plattform springen.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Step-Ups',
    nameDe: 'Aufsteigen',
    description: 'Step up onto bench alternating legs.',
    descriptionDe: 'Mit abwechselnden Beinen auf eine Bank steigen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Sumo Squat',
    nameDe: 'Sumo Kniebeuge',
    description: 'Wide-stance squat with toes pointed out.',
    descriptionDe: 'Kniebeuge mit breitem Stand und nach außen gedrehten Zehen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Sissy Squat',
    nameDe: 'Sissy Kniebeuge',
    description: 'Lean back while squatting to emphasize quads.',
    descriptionDe: 'Bei der Kniebeuge nach hinten lehnen für den Quadrizeps.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Pistol Squat',
    nameDe: 'Einbeinige Kniebeuge',
    description: 'Single-leg squat with other leg extended forward.',
    descriptionDe: 'Einbeinige Kniebeuge mit dem anderen Bein nach vorne gestreckt.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Jump Squats',
    nameDe: 'Sprungkniebeugen',
    description: 'Squat and jump explosively at top.',
    descriptionDe: 'Kniebeuge und oben explosiv abspringen.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Barbell Lunges',
    nameDe: 'Langhantel Ausfallschritte',
    description: 'Lunges with barbell on back.',
    descriptionDe: 'Ausfallschritte mit Langhantel auf dem Rücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Dumbbell Lunges',
    nameDe: 'Kurzhantel Ausfallschritte',
    description: 'Lunges holding dumbbells at sides.',
    descriptionDe: 'Ausfallschritte mit Kurzhanteln seitlich.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Glute Bridge',
    nameDe: 'Gesäßbrücke',
    description: 'Lift hips from floor while shoulders stay down.',
    descriptionDe: 'Hüfte vom Boden heben, Schultern bleiben unten.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Hip Thrust',
    nameDe: 'Hüftheben',
    description: 'Thrust hips up with upper back on bench.',
    descriptionDe: 'Hüfte nach oben drücken mit dem oberen Rücken auf der Bank.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Barbell Hip Thrust',
    nameDe: 'Langhantel Hüftheben',
    description: 'Hip thrust with barbell across hips.',
    descriptionDe: 'Hüftheben mit Langhantel quer über die Hüfte.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Single-Leg Press',
    nameDe: 'Einbeinige Beinpresse',
    description: 'Leg press performed one leg at a time.',
    descriptionDe: 'Beinpresse mit einem Bein auf einmal.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Adductor Machine',
    nameDe: 'Adduktoren Maschine',
    description: 'Squeeze legs together on machine for inner thighs.',
    descriptionDe: 'Beine an der Maschine zusammendrücken für die Innenschenkel.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Abductor Machine',
    nameDe: 'Abduktoren Maschine',
    description: 'Push legs apart on machine for outer hips.',
    descriptionDe: 'Beine an der Maschine auseinanderdrücken für die äußere Hüfte.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Nordic Hamstring Curl',
    nameDe: 'Nordisches Beinbeugen',
    description: 'Lower body forward with knees fixed.',
    descriptionDe: 'Körper mit fixierten Knien nach vorne absenken.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Smith Machine Squat',
    nameDe: 'Smith Machine Kniebeuge',
    description: 'Squat using Smith machine for guided path.',
    descriptionDe: 'Kniebeuge an der Smith Machine für geführte Bewegungsbahn.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),
  Exercise(
    name: 'Leg Press High Feet',
    nameDe: 'Beinpresse hohe Fußposition',
    description: 'Leg press with feet high on platform for glute emphasis.',
    descriptionDe: 'Beinpresse mit hoher Fußposition auf der Platte für das Gesäß.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.legs],
    isCustom: false,
  ),

  // ── ABS (19) ──────────────────────────────────────────────────────────────
  Exercise(
    name: 'Plank',
    nameDe: 'Unterarmstütz',
    description: 'Hold rigid position on forearms and toes.',
    descriptionDe: 'Starre Position auf Unterarmen und Zehenspitzen halten.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Side Plank',
    nameDe: 'Seitlicher Unterarmstütz',
    description: 'Hold plank position on one forearm with body sideways.',
    descriptionDe: 'Stützposition seitlich auf einem Unterarm halten.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Crunches',
    nameDe: 'Crunches',
    description: 'Lift shoulders off floor while lying on back.',
    descriptionDe: 'Schultern vom Boden heben, auf dem Rücken liegend.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Crunch Machine',
    nameDe: 'Bauchpressmaschine',
    description: 'Perform seated crunches using the machine by contracting your abs while controlling the movement.',
    descriptionDe: 'Sitzende Crunches an der Maschine durch Anspannen der Bauchmuskulatur.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Bicycle Crunches',
    nameDe: 'Fahrrad Crunches',
    description: 'Alternate touching elbow to opposite knee in crunch motion.',
    descriptionDe: 'Abwechselnd Ellbogen zum gegenüberliegenden Knie in Crunch-Bewegung.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Reverse Crunches',
    nameDe: 'Umgekehrte Crunches',
    description: 'Lift hips off floor bringing knees to chest.',
    descriptionDe: 'Hüfte vom Boden heben und Knie zur Brust bringen.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Cable Crunches',
    nameDe: 'Kabelzug Crunches',
    description: 'Crunch down with rope attachment from high pulley.',
    descriptionDe: 'Mit Seilaufsatz vom oberen Kabelzug nach unten crunchen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Hanging Leg Raises',
    nameDe: 'Hängendes Beinheben',
    description: 'Hang from bar and raise legs to horizontal.',
    descriptionDe: 'An der Stange hängen und Beine auf Horizontale heben.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Hanging Knee Raises',
    nameDe: 'Hängendes Knieheben',
    description: 'Hang from bar and bring knees to chest.',
    descriptionDe: 'An der Stange hängen und Knie zur Brust bringen.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Ab Wheel Rollout',
    nameDe: 'Bauchradroller',
    description: 'Roll ab wheel forward extending body.',
    descriptionDe: 'Bauchrad vorwärts rollen und den Körper strecken.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Russian Twists',
    nameDe: 'Russische Drehungen',
    description: 'Rotate torso side to side while seated with feet elevated.',
    descriptionDe: 'Oberkörper seitlich drehen, sitzend mit erhobenen Füßen.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Oblique Crunches',
    nameDe: 'Schräge Crunches',
    description: 'Crunch to side to target obliques.',
    descriptionDe: 'Seitlich crunchen für die schräge Bauchmuskulatur.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Mountain Climbers',
    nameDe: 'Bergsteiger',
    description: 'Alternate driving knees to chest in plank position.',
    descriptionDe: 'Knie abwechselnd zur Brust ziehen in der Stützposition.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs, MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: 'Dead Bug',
    nameDe: 'Toter Käfer',
    description: 'Alternate extending opposite arm and leg while lying on back.',
    descriptionDe: 'Auf dem Rücken liegend abwechselnd gegenüberliegenden Arm und Bein strecken.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Leg Raises',
    nameDe: 'Beinheben',
    description: 'Raise straight legs from floor while lying on back.',
    descriptionDe: 'Gestreckte Beine vom Boden heben, auf dem Rücken liegend.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'V-Ups',
    nameDe: 'V-Sit-Ups',
    description: 'Simultaneously raise legs and torso forming V shape.',
    descriptionDe: 'Beine und Oberkörper gleichzeitig heben und V-Form bilden.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Pallof Press',
    nameDe: 'Pallof Drücken',
    description: 'Press cable straight out resisting rotation.',
    descriptionDe: 'Kabel gerade nach vorne drücken und Rotation widerstehen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Woodchoppers',
    nameDe: 'Holzfäller',
    description: 'Rotate torso bringing cable from high to low across body.',
    descriptionDe: 'Oberkörper drehen und Kabel diagonal von oben nach unten führen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),
  Exercise(
    name: 'Decline Sit-Ups',
    nameDe: 'Schräge Sit-Ups',
    description: 'Sit-ups performed on decline bench.',
    descriptionDe: 'Sit-Ups auf der negativen Schrägbank ausgeführt.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.abs],
    isCustom: false,
  ),

  // ── FULL BODY (10) ────────────────────────────────────────────────────────
  Exercise(
    name: 'Burpees',
    nameDe: 'Burpees',
    description: 'Squat, jump back to plank, do push-up, jump forward, jump up.',
    descriptionDe: 'In die Hocke, in den Liegestütz springen, Liegestütz machen, vorspringen, hochspringen.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: 'Clean and Press',
    nameDe: 'Umsetzen und Stoßen',
    description: 'Clean barbell to shoulders then press overhead.',
    descriptionDe: 'Langhantel zu den Schultern umsetzen und dann über den Kopf drücken.',
    type: ExerciseType.cardio,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: 'Kettlebell Swings',
    nameDe: 'Kettlebell Schwingen',
    description: 'Swing kettlebell between legs then up to shoulder height.',
    descriptionDe: 'Kettlebell zwischen den Beinen durchschwingen und auf Schulterhöhe heben.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: 'Thrusters',
    nameDe: 'Thrusters',
    description: 'Squat with dumbbells then press overhead in one motion.',
    descriptionDe: 'Kniebeuge mit Kurzhanteln und in einer Bewegung über den Kopf drücken.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: 'Battle Ropes',
    nameDe: 'Kampfseile',
    description: 'Alternate whipping heavy ropes up and down.',
    descriptionDe: 'Schwere Seile abwechselnd auf und ab schlagen.',
    type: ExerciseType.cardio,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: 'Box Jumps',
    nameDe: 'Kastensprünge',
    description: 'Jump explosively onto elevated platform.',
    descriptionDe: 'Explosiv auf eine erhöhte Plattform springen.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: 'Medicine Ball Slams',
    nameDe: 'Medizinball Schmetterwurf',
    description: 'Slam medicine ball to ground with force.',
    descriptionDe: 'Medizinball mit Kraft auf den Boden schmettern.',
    type: ExerciseType.calisthenics,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: 'Turkish Get-Up',
    nameDe: 'Türkisches Aufstehen',
    description: 'Complex movement from lying to standing while holding weight overhead.',
    descriptionDe: 'Komplexe Bewegung vom Liegen zum Stehen mit Gewicht über dem Kopf.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: "Farmer's Walk",
    nameDe: 'Bauerngang',
    description: 'Walk while carrying heavy weights at sides.',
    descriptionDe: 'Mit schweren Gewichten seitlich gehen.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
  Exercise(
    name: 'Sled Push',
    nameDe: 'Schlittenschieben',
    description: 'Push weighted sled across floor.',
    descriptionDe: 'Beladenen Schlitten über den Boden schieben.',
    type: ExerciseType.strength,
    targetMuscleGroups: [MuscleGroup.fullBody],
    isCustom: false,
  ),
];
