import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:ForgeForm/core/app_database.dart';
import 'package:ForgeForm/feature/workout_planning/data/models/exercise.dart';

Future<void> seedExercisesIfEmpty(AppDatabase db) async {
  // Check if exercises already exist
  final existingExercises = await db.exerciseDao.getAllExercises();
  if (existingExercises.isNotEmpty) {
    return; // Database already has exercises
  }

  // Define all exercises
  final exercises = <Exercise>[
    // CHEST EXERCISES (20)
    Exercise(
      name: 'Barbell Bench Press',
      description:
          'Lie on a flat bench and press the barbell from chest to full arm extension.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Incline Barbell Bench Press',
      description:
          'Bench press performed on an incline bench to target upper chest.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Incline Barbell Bench Press(Smith Machine)',
      description:
          'Bench press performed on an incline bench to target upper chest.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Decline Barbell Bench Press',
      description: 'Bench press on a decline bench targeting lower chest.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Bench Press',
      description:
          'Press dumbbells from chest level while lying on a flat bench.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Incline Dumbbell Press',
      description:
          'Dumbbell press on an incline bench for upper chest development.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Decline Dumbbell Press',
      description: 'Dumbbell press on a decline bench targeting lower chest.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Flyes',
      description:
          'Lying dumbbell flyes with arms in arc motion to stretch and contract chest.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Incline Dumbbell Flyes',
      description:
          'Flyes performed on incline bench for upper chest isolation.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Cable Crossover',
      description:
          'Stand between cable pulleys and bring handles together in front of chest.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Low Cable Crossover',
      description: 'Cable crossover from low position targeting upper chest.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Push-Ups',
      description:
          'Classic bodyweight exercise pushing body up from prone position.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Decline Push-Ups',
      description: 'Push-ups with feet elevated to increase difficulty.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dips (Chest)',
      description:
          'Lean forward on parallel bars and dip down to target chest.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Cable Flyes',
      description: 'Cable flyes from mid-height for chest isolation.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Pec Deck Machine',
      description: 'Machine-based fly movement for chest isolation.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Chest Press Machine',
      description: 'Machine press for controlled chest development.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Incline Cable Flyes',
      description: 'Cable flyes from low position for upper chest.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Close-Grip Bench Press',
      description:
          'Bench press with narrow grip emphasizing inner chest and triceps.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest, MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Wide-Grip Bench Press',
      description: 'Bench press with wide grip for outer chest emphasis.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Smith Machine Bench Press',
      description: 'Guided bench press using Smith machine for stability.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),

    // BACK EXERCISES (25)
    Exercise(
      name: 'Barbell Deadlift',
      description:
          'Lift barbell from floor to standing position with straight back.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back, MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Romanian Deadlift',
      description:
          'Deadlift variation with slight knee bend emphasizing hamstrings and lower back.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back, MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Sumo Deadlift',
      description: 'Deadlift with wide stance and toes pointed out.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back, MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Bent Over Barbell Row',
      description:
          'Bent forward, row barbell to lower chest with elbows close.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'T-Bar Row',
      description:
          'Row using landmine barbell setup for thick back development.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Pendlay Row',
      description:
          'Explosive barbell row from floor with torso parallel to ground.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Pull-Ups',
      description: 'Pull body up to bar with palms facing away.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Chin-Ups',
      description: 'Pull body up to bar with palms facing toward you.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.back, MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Lat Pulldown',
      description: 'Pull cable bar down to upper chest while seated.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Wide-Grip Lat Pulldown',
      description: 'Lat pulldown with wide grip for lat width.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Close-Grip Lat Pulldown',
      description: 'Lat pulldown with close grip for lat thickness.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Seated Cable Row',
      description:
          'Pull cable handle to torso while seated with legs extended.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'One-Arm Dumbbell Row',
      description: 'Row dumbbell to hip with one hand while braced on bench.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Row',
      description: 'Bent over row with both dumbbells simultaneously.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Barbell Shrug',
      description: 'Shrug shoulders up while holding barbell to work traps.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Kelso Shrugs',
      description:
          'Lean forward slightly and shrug the shoulders back and up to target the mid-traps and rhomboids.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Shrug',
      description: 'Shrug shoulders with dumbbells for trap development.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Face Pulls',
      description: 'Pull rope to face level for rear delts and upper back.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back, MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Straight-Arm Pulldown',
      description: 'Push bar down with straight arms to isolate lats.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Machine Row',
      description: 'Rowing movement on machine for controlled back work.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Inverted Row',
      description: 'Bodyweight row under bar or table.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Hyperextensions',
      description: 'Extend torso on hyperextension bench for lower back.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Good Mornings',
      description: 'Bend forward at hips with barbell on back.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back, MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Rack Pulls',
      description: 'Deadlift from elevated position for upper back emphasis.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Cable Shrugs',
      description: 'Shrug movement using cable for constant tension.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Rope Face Pulls',
      description: 'Face pulls with rope attachment for rear delts.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.back, MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),

    // SHOULDER EXERCISES (18)
    Exercise(
      name: 'Overhead Press',
      description: 'Press barbell from shoulders to overhead lockout.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Military Press',
      description: 'Strict overhead press with feet together.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Shoulder Press',
      description: 'Press dumbbells overhead while seated or standing.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Arnold Press',
      description: 'Dumbbell press with rotation from palms-in to palms-out.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Seated Dumbbell Press',
      description: 'Seated variation of dumbbell overhead press.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Lateral Raises',
      description: 'Raise arms to sides for side delt development.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Lateral Raises',
      description: 'Raise dumbbells out to sides to shoulder height.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Cable Lateral Raises',
      description: 'Lateral raises using cable for constant tension.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Front Raises',
      description: 'Raise weight in front of body to shoulder height.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Barbell Front Raises',
      description: 'Front raises holding barbell with both hands.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Rear Delt Flyes',
      description: 'Bent over flyes for rear deltoid isolation.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Reverse Pec Deck',
      description: 'Machine fly for rear delts with chest against pad.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Upright Row',
      description: 'Pull bar up along torso to shoulder height.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Bradford Press',
      description: 'Alternate pressing in front and behind head.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Push Press',
      description: 'Overhead press with leg drive for momentum.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Machine Shoulder Press',
      description: 'Guided overhead press on machine.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Cable Front Raises',
      description: 'Front raises using cable for constant tension.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Seated Lateral Raises',
      description: 'Lateral raises performed while seated for strict form.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.shoulders],
      imageUrl: null,
      isCustom: false,
    ),

    // BICEPS EXERCISES (12)
    Exercise(
      name: 'Barbell Curl',
      description: 'Curl barbell from thighs to shoulders with supinated grip.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'EZ-Bar Curl',
      description: 'Curl EZ-bar to reduce wrist strain.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Curl',
      description: 'Alternating or simultaneous dumbbell curls.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Hammer Curl',
      description:
          'Curl dumbbells with neutral grip (palms facing each other).',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Preacher Curl',
      description: 'Curl on preacher bench for strict bicep isolation.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Concentration Curl',
      description: 'Single-arm curl seated with elbow braced on inner thigh.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Cable Curl',
      description: 'Bicep curl using cable machine for constant tension.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Incline Dumbbell Curl',
      description: 'Curl on incline bench for full bicep stretch.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Spider Curl',
      description: 'Curl over incline bench with chest against pad.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Reverse Curl',
      description: 'Curl with pronated grip to work forearms and biceps.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Cable Hammer Curl',
      description: 'Hammer curls using rope attachment on cable.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: '21s',
      description:
          'Barbell curl variation: 7 bottom half, 7 top half, 7 full range.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.biceps],
      imageUrl: null,
      isCustom: false,
    ),

    // TRICEPS EXERCISES (12)
    Exercise(
      name: 'Tricep Dips',
      description: 'Dip between parallel bars keeping torso upright.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Close-Grip Bench Press',
      description: 'Bench press with hands close together for tricep emphasis.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.triceps, MuscleGroup.chest],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Skull Crushers',
      description: 'Lower bar to forehead and extend arms while lying down.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'EZ-Bar Skull Crushers',
      description: 'Skull crushers using EZ-bar for wrist comfort.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Overhead Tricep Extension',
      description: 'Extend weight overhead from behind head.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Overhead Extension',
      description: 'Single dumbbell held with both hands extended overhead.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Cable Pushdown',
      description: 'Push cable bar down by extending elbows.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Rope Pushdown',
      description: 'Cable pushdown with rope for full tricep contraction.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Tricep Kickbacks',
      description: 'Bent over, extend arm back fully to work triceps.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Kickbacks',
      description: 'Single-arm kickbacks using dumbbells.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Diamond Push-Ups',
      description: 'Push-ups with hands forming diamond shape.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Bench Dips',
      description: 'Dips using bench with feet on ground or elevated.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.triceps],
      imageUrl: null,
      isCustom: false,
    ),

    // LEG EXERCISES (35)
    Exercise(
      name: 'Barbell Squat',
      description: 'Squat with barbell on back to parallel or below.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Front Squat',
      description: 'Squat with barbell held on front of shoulders.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Goblet Squat',
      description: 'Squat holding dumbbell or kettlebell at chest.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Bulgarian Split Squat',
      description: 'Single-leg squat with rear foot elevated.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Leg Press',
      description: 'Press weight platform away with legs.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Hack Squat',
      description: 'Squat on machine with back against pad.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Stiff-Leg Deadlift',
      description: 'Deadlift with straight legs for hamstring emphasis.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Walking Lunges',
      description: 'Lunge forward alternating legs while walking.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Reverse Lunges',
      description: 'Step backward into lunge position.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Forward Lunges',
      description: 'Step forward into lunge and return to start.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Lying Leg Curls',
      description: 'Curl legs up on machine while lying face down.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Seated Leg Curls',
      description: 'Leg curl performed in seated position.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Leg Extensions',
      description: 'Extend legs on machine to work quadriceps.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Leg Press Calf Raise',
      description: 'Calf raises performed on leg press machine.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Standing Calf Raises',
      description: 'Raise up on toes on calf machine while standing.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Seated Calf Raises',
      description: 'Calf raises performed seated with weight on knees.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Donkey Calf Raises',
      description: 'Calf raises bent over with weight on lower back.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Box Jumps',
      description: 'Jump explosively onto elevated box or platform.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Step-Ups',
      description: 'Step up onto bench alternating legs.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Sumo Squat',
      description: 'Wide-stance squat with toes pointed out.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Sissy Squat',
      description: 'Lean back while squatting to emphasize quads.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Pistol Squat',
      description: 'Single-leg squat with other leg extended forward.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Jump Squats',
      description: 'Squat and jump explosively at top.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Barbell Lunges',
      description: 'Lunges with barbell on back.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dumbbell Lunges',
      description: 'Lunges holding dumbbells at sides.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Glute Bridge',
      description: 'Lift hips from floor while shoulders stay down.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Hip Thrust',
      description: 'Thrust hips up with upper back on bench.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Barbell Hip Thrust',
      description: 'Hip thrust with barbell across hips.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Single-Leg Press',
      description: 'Leg press performed one leg at a time.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Adductor Machine',
      description: 'Squeeze legs together on machine for inner thighs.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Abductor Machine',
      description: 'Push legs apart on machine for outer hips.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Nordic Hamstring Curl',
      description: 'Lower body forward with knees fixed.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Smith Machine Squat',
      description: 'Squat using Smith machine for guided path.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Leg Press High Feet',
      description: 'Leg press with feet high on platform for glute emphasis.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.legs],
      imageUrl: null,
      isCustom: false,
    ),

    // ABS EXERCISES (18)
    Exercise(
      name: 'Plank',
      description: 'Hold rigid position on forearms and toes.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Side Plank',
      description: 'Hold plank position on one forearm with body sideways.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Crunches',
      description: 'Lift shoulders off floor while lying on back.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Crunch Machine',
      description:
          'Perform seated crunches using the machine by contracting your abs while controlling the movement.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Bicycle Crunches',
      description:
          'Alternate touching elbow to opposite knee in crunch motion.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Reverse Crunches',
      description: 'Lift hips off floor bringing knees to chest.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Cable Crunches',
      description: 'Crunch down with rope attachment from high pulley.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Hanging Leg Raises',
      description: 'Hang from bar and raise legs to horizontal.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Hanging Knee Raises',
      description: 'Hang from bar and bring knees to chest.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Ab Wheel Rollout',
      description: 'Roll ab wheel forward extending body.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Russian Twists',
      description: 'Rotate torso side to side while seated with feet elevated.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Oblique Crunches',
      description: 'Crunch to side to target obliques.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Mountain Climbers',
      description: 'Alternate driving knees to chest in plank position.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs, MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Dead Bug',
      description:
          'Alternate extending opposite arm and leg while lying on back.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Leg Raises',
      description: 'Raise straight legs from floor while lying on back.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'V-Ups',
      description: 'Simultaneously raise legs and torso forming V shape.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Pallof Press',
      description: 'Press cable straight out resisting rotation.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Woodchoppers',
      description: 'Rotate torso bringing cable from high to low across body.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Decline Sit-Ups',
      description: 'Sit-ups performed on decline bench.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.abs],
      imageUrl: null,
      isCustom: false,
    ),

    // FULL BODY EXERCISES (10)
    Exercise(
      name: 'Burpees',
      description:
          'Squat, jump back to plank, do push-up, jump forward, jump up.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Clean and Press',
      description: 'Clean barbell to shoulders then press overhead.',
      type: ExerciseType.cardio,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Kettlebell Swings',
      description: 'Swing kettlebell between legs then up to shoulder height.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Thrusters',
      description: 'Squat with dumbbells then press overhead in one motion.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Battle Ropes',
      description: 'Alternate whipping heavy ropes up and down.',
      type: ExerciseType.cardio,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Box Jumps',
      description: 'Jump explosively onto elevated platform.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Medicine Ball Slams',
      description: 'Slam medicine ball to ground with force.',
      type: ExerciseType.calisthenics,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Turkish Get-Up',
      description:
          'Complex movement from lying to standing while holding weight overhead.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: "Farmer's Walk",
      description: 'Walk while carrying heavy weights at sides.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
    Exercise(
      name: 'Sled Push',
      description: 'Push weighted sled across floor.',
      type: ExerciseType.strength,
      targetMuscleGroups: [MuscleGroup.fullBody],
      imageUrl: null,
      isCustom: false,
    ),
  ];
  // Insert all exercises
  for (final exercise in exercises) {
    // Convert Exercise model to ExerciseTableCompanion expected by the DAO.
    final companion = ExerciseTableCompanion(
      name: Value(exercise.name),
      description: Value(exercise.description),
      // store enum as index (int)
      type: Value(exercise.type.index),
      // serialize list of enums to JSON of indices
      targetMuscleGroups: Value(
        exercise.targetMuscleGroups.map((m) => m.index.toString()).join(','),
      ),
      imageUrl: Value(exercise.imageUrl),
      isCustom: Value(exercise.isCustom),
    );

    await db.exerciseDao.saveExercise(companion);
  }
}
