/// A safe-to-write filesystem name for a chat attachment, derived from data
/// the *peer* controls.
///
/// [ChatAttachmentRef.name] and [ChatAttachmentRef.id] are both
/// client-generated by whoever sent the message — see the doc comment on
/// `ChatAttachmentRef.id`. Until this file existed, `name` was only ever
/// rendered as text (a document tile's label) and `id` was only ever used as
/// a lookup key, so nothing needed to distrust either. The moment either
/// becomes a path segment — writing a temp file to hand to the OS, or to
/// this device's permanent attachment store — that stops being true: a peer
/// who names an attachment `../../../etc/whatever` or sends `..` as its id
/// is choosing where bytes land on someone else's disk, not what a bubble
/// says. See docs/chat-attachments.md §17.
library;

/// Reserved device names on Windows — matching one, with or without an
/// extension, opens a device rather than a file. Case-insensitive.
const _windowsReservedNames = {
  'con', 'prn', 'aux', 'nul',
  'com1', 'com2', 'com3', 'com4', 'com5', 'com6', 'com7', 'com8', 'com9',
  'lpt1', 'lpt2', 'lpt3', 'lpt4', 'lpt5', 'lpt6', 'lpt7', 'lpt8', 'lpt9',
};

const _maxNameLength = 100;
const _maxFallbackIdLength = 40;

/// The subdirectory under the OS temp directory a document is written to
/// before being handed to the OS (`attachment_opener_io.dart`) — named here,
/// a plain-Dart file compiled on every platform, so `AttachmentStore`'s
/// sign-out sweep (compiled everywhere too) can reference the same name
/// without importing a `dart:io`-only file.
const chatDocsOpenDirName = 'forgeform_chat_docs';

/// A file name safe to write under a fixed directory on every platform this
/// app ships on, derived from [rawName] (`ChatAttachmentRef.name`).
///
/// [fallbackId] (typically `ChatAttachmentRef.id`) is used only when nothing
/// usable survives sanitising [rawName] — and is itself sanitised, since it
/// is exactly as peer-controlled as the name. [mime] picks the fallback's
/// extension so a handler can still be resolved by extension, which is how
/// both `open_filex` and the Windows shell pick an app.
String safeAttachmentFileName(
  String rawName, {
  required String fallbackId,
  required String mime,
}) {
  final cleaned = _sanitizeSegment(rawName);
  if (cleaned != null) return cleaned;

  final safeId = _sanitizeFallbackId(fallbackId);
  final ext = _extensionForMime(mime);
  return ext == null ? 'chat_doc_$safeId' : 'chat_doc_$safeId.$ext';
}

/// Null on anything that doesn't leave a usable name behind — every case
/// funnels to the id-based fallback above rather than trying to patch a
/// name that was never a real name.
String? _sanitizeSegment(String rawName) {
  // Only the last path segment survives, on either separator. This single
  // step is what defeats `../../etc/passwd`, `..\..\windows\system32\x.dll`
  // and an absolute path alike — everything before the last slash (or
  // backslash) is discarded, not "cleaned".
  final parts = rawName.split(RegExp(r'[\\/]'));
  var name = parts.isEmpty ? '' : parts.last;

  // Control characters (including NUL) and the characters Windows forbids
  // in a file name outright.
  name = name.replaceAll(RegExp(r'[\x00-\x1f<>:"|?*]'), '');

  // Trailing dots and spaces are stripped silently by Windows, so a name
  // that looks validated (`report.pdf.`) would not be the file that lands.
  name = name.replaceAll(RegExp(r'[. ]+$'), '');

  if (name.isEmpty || name == '.' || name == '..') return null;

  final dotIndex = name.lastIndexOf('.');
  final stem = dotIndex <= 0 ? name : name.substring(0, dotIndex);
  if (_windowsReservedNames.contains(stem.toLowerCase())) return null;

  if (name.length > _maxNameLength) {
    name = _truncatePreservingExtension(name, _maxNameLength);
  }

  return name.isEmpty ? null : name;
}

String _truncatePreservingExtension(String name, int maxLength) {
  final dotIndex = name.lastIndexOf('.');
  // A dot only counts as an extension separator when it leaves both a
  // non-empty stem and a short, plausible extension behind — otherwise
  // "truncate the stem" would eat the entire name for something like
  // `.htaccess` or a name with no extension at all.
  final hasExtension =
      dotIndex > 0 && (name.length - dotIndex - 1) <= 10;
  if (!hasExtension) return name.substring(0, maxLength);

  final ext = name.substring(dotIndex);
  final keepForStem = maxLength - ext.length;
  if (keepForStem <= 0) return name.substring(0, maxLength);
  return name.substring(0, keepForStem) + ext;
}

String _sanitizeFallbackId(String fallbackId) {
  final safe = safeAttachmentIdSegment(fallbackId, fallback: 'unknown');
  return safe.length > _maxFallbackIdLength
      ? safe.substring(0, _maxFallbackIdLength)
      : safe;
}

/// A peer-controlled attachment id, reduced to characters safe to use as a
/// whole filesystem path segment on every platform this app ships on.
///
/// `ChatAttachmentRef.id` is client-generated by whoever *sent* the
/// message — see this file's own doc comment for what that means once a
/// value crosses from "rendered as text" to "used as a path". It was
/// already being interpolated directly into a path in three places that
/// predate this file: `_VideoTile` and `_AudioTile`'s temp playback files
/// (`chat_video_<id>.bin` / `chat_audio_<id>.bin`), and
/// `AttachmentStore._filePath`, which writes into *permanent* app-private
/// storage. All three now route through this function.
String safeAttachmentIdSegment(String id, {String fallback = 'attachment'}) {
  final safe = id.replaceAll(RegExp(r'[^A-Za-z0-9_-]'), '');
  return safe.isEmpty ? fallback : safe;
}

/// A short, fixed table rather than a package — this only ever needs to
/// pick an extension well enough for the OS to find a handler, not to be a
/// general MIME registry.
String? _extensionForMime(String mime) {
  switch (mime.toLowerCase()) {
    case 'application/pdf':
      return 'pdf';
    case 'application/msword':
      return 'doc';
    case 'application/vnd.openxmlformats-officedocument.wordprocessingml.document':
      return 'docx';
    case 'application/vnd.ms-excel':
      return 'xls';
    case 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':
      return 'xlsx';
    case 'application/vnd.ms-powerpoint':
      return 'ppt';
    case 'application/vnd.openxmlformats-officedocument.presentationml.presentation':
      return 'pptx';
    case 'text/plain':
      return 'txt';
    case 'text/csv':
      return 'csv';
    case 'application/zip':
      return 'zip';
    case 'image/jpeg':
      return 'jpg';
    case 'image/png':
      return 'png';
    case 'image/heic':
      return 'heic';
    case 'video/mp4':
      return 'mp4';
    case 'audio/mpeg':
      return 'mp3';
    case 'audio/mp4':
    case 'audio/m4a':
      return 'm4a';
    case 'application/octet-stream':
      return null;
    default:
      // Anything of the shape "type/subtype" — take the subtype verbatim,
      // stripped of the `x-`/vendor prefixes and parameters a real MIME
      // value can carry (`application/vnd.foo+xml; charset=…`).
      final slash = mime.indexOf('/');
      if (slash < 0 || slash == mime.length - 1) return null;
      var subtype = mime.substring(slash + 1);
      final semicolon = subtype.indexOf(';');
      if (semicolon >= 0) subtype = subtype.substring(0, semicolon);
      final plus = subtype.indexOf('+');
      if (plus >= 0) subtype = subtype.substring(0, plus);
      if (subtype.startsWith('x-')) subtype = subtype.substring(2);
      if (subtype.startsWith('vnd.')) subtype = subtype.substring(4);
      subtype = subtype.replaceAll(RegExp(r'[^A-Za-z0-9]'), '');
      return subtype.isEmpty ? null : subtype.toLowerCase();
  }
}
