#!/usr/bin/env python3
"""
Generates German exercise translations using a comprehensive gym-terminology
substitution dictionary — no API key required.

Run from fittnes_tracker/:
    python3 tool/translate_local.py

Outputs: tool/translations_de.json
Then run: python3 tool/generate_seeds.py
"""
import csv, json, os, re

# ── Word / phrase substitution tables ───────────────────────────────────────
# Longer phrases first so they are matched before their sub-words.

PHRASE_MAP = [
    # ── Equipment ────────────────────────────────────────────────────────────
    ("Olympic Barbell", "Olympia-Langhantel"),
    ("Barbell", "Langhantel"),
    ("Dumbbells", "Kurzhanteln"),
    ("Dumbbell", "Kurzhantel"),
    ("Kettlebells", "Kettlebells"),
    ("Kettlebell", "Kettlebell"),
    ("EZ-Bar", "EZ-Stange"),
    ("EZ Bar", "EZ-Stange"),
    ("Trap Bar", "Trap-Stange"),
    ("Axle", "Achse"),
    ("Smith Machine", "Smith-Maschine"),
    ("Cable Machine", "Kabelzug-Maschine"),
    ("Cable", "Kabelzug"),
    ("Machine", "Maschine"),
    ("Resistance Band", "Widerstandsband"),
    ("Elastic Band", "Elastikband"),
    ("Band", "Band"),
    ("Medicine Ball", "Medizinball"),
    ("Swiss Ball", "Pezziball"),
    ("Stability Ball", "Stabilityball"),
    ("Exercise Ball", "Trainingsball"),
    ("Bosu Ball", "Bosu-Ball"),
    ("Foam Roller", "Schaumstoffrolle"),
    ("Foam Roll", "Schaumstoffrolle"),
    ("Suspension", "Schlingentrainer"),
    ("TRX", "TRX"),
    ("Pull-Up Bar", "Klimmzugstange"),
    ("Chin-Up Bar", "Klimmzugstange"),
    ("Gymnastic Rings", "Turnringe"),
    ("Rings", "Turnringe"),
    ("Atlas Stone", "Atlas-Stein"),
    ("Log", "Stamm"),
    ("Tire", "Reifen"),
    ("Sled", "Schlitten"),
    ("Sandbag", "Sandsack"),
    ("Rope", "Seil"),
    ("Chains", "Ketten"),
    ("Plate", "Scheibe"),
    ("Weight Plate", "Gewichtsscheibe"),
    ("Balance Board", "Gleichgewichtsbrett"),
    ("Step", "Stufe"),
    ("Bench", "Bank"),
    # ── Exercise types / movements ────────────────────────────────────────────
    ("Bench Press", "Bankdrücken"),
    ("Overhead Press", "Überkopfdrücken"),
    ("Shoulder Press", "Schulterdrücken"),
    ("Chest Press", "Brustdrücken"),
    ("Hip Press", "Hüftdrücken"),
    ("Leg Press", "Beinpresse"),
    ("Calf Press", "Wadendrücken"),
    ("Press", "Drücken"),
    ("Pull-Down", "Latzug"),
    ("Pulldown", "Latzug"),
    ("Pull-Up", "Klimmzug"),
    ("Pull Up", "Klimmzug"),
    ("Pullup", "Klimmzug"),
    ("Chin-Up", "Klimmzug (Enger Griff)"),
    ("Chin Up", "Klimmzug (Enger Griff)"),
    ("Push-Up", "Liegestütz"),
    ("Push Up", "Liegestütz"),
    ("Pushup", "Liegestütz"),
    ("Dips", "Dips"),
    ("Dip", "Dip"),
    ("Hip Thrust", "Hüftstrecken"),
    ("Hip Extension", "Hüftstreckung"),
    ("Hip Adduction", "Hüftadduktion"),
    ("Hip Abduction", "Hüftabduktion"),
    ("Hip Flexion", "Hüftbeugung"),
    ("Deadlift", "Kreuzheben"),
    ("Romanian Deadlift", "Rumänisches Kreuzheben"),
    ("Stiff-Leg Deadlift", "Stiff-Leg Kreuzheben"),
    ("Squat", "Kniebeuge"),
    ("Front Squat", "Frontkniebeuge"),
    ("Hack Squat", "Hack-Kniebeuge"),
    ("Box Squat", "Box-Kniebeuge"),
    ("Goblet Squat", "Goblet-Kniebeuge"),
    ("Overhead Squat", "Überkopf-Kniebeuge"),
    ("Sumo Squat", "Sumo-Kniebeuge"),
    ("Wall Squat", "Wandkniebeuge"),
    ("Lunge", "Ausfallschritt"),
    ("Walking Lunge", "Ausfallschritte gehend"),
    ("Lateral Lunge", "Seitlicher Ausfallschritt"),
    ("Reverse Lunge", "Rückwärtiger Ausfallschritt"),
    ("Bicep Curl", "Bizepscurl"),
    ("Biceps Curl", "Bizepscurl"),
    ("Hammer Curl", "Hammer-Curl"),
    ("Preacher Curl", "Preacher-Curl"),
    ("Concentration Curl", "Konzentrations-Curl"),
    ("Reverse Curl", "Reverse-Curl"),
    ("Wrist Curl", "Handgelenk-Curl"),
    ("Curl", "Curl"),
    ("Tricep Extension", "Trizepsstreckung"),
    ("Triceps Extension", "Trizepsstreckung"),
    ("Overhead Extension", "Überkopf-Streckung"),
    ("Skull Crusher", "Stirndrücken"),
    ("Kickback", "Kickback"),
    ("Extension", "Streckung"),
    ("Leg Curl", "Beincurl"),
    ("Leg Extension", "Beinstreckung"),
    ("Hamstring Curl", "Hamstring-Curl"),
    ("Calf Raise", "Wadenlifte"),
    ("Raise", "Heben"),
    ("Lateral Raise", "Seitheben"),
    ("Front Raise", "Frontheben"),
    ("Upright Row", "Aufrechtes Rudern"),
    ("Bent-Over Row", "Vorgebeugtes Rudern"),
    ("Bent Over Row", "Vorgebeugtes Rudern"),
    ("Seated Row", "Sitzrudern"),
    ("Cable Row", "Kabelzugrudern"),
    ("T-Bar Row", "T-Stangenrudern"),
    ("Row", "Rudern"),
    ("Chest Fly", "Butterfly"),
    ("Fly", "Fliegender"),
    ("Flye", "Fliegender"),
    ("Lat Pulldown", "Latzug"),
    ("Lat Pull-Down", "Latzug"),
    ("Shrug", "Schulterziehen"),
    ("Face Pull", "Gesichtszug"),
    ("Pull-Through", "Kabel-Durchzug"),
    ("Pull Through", "Kabel-Durchzug"),
    ("Good Morning", "Good Morning"),
    ("Hip Hinge", "Hüftscharnier"),
    ("Romanian", "Rumänisch"),
    ("Nordic", "Nordisch"),
    ("Glute Bridge", "Gesäßbrücke"),
    ("Glute Ham Raise", "Gesäß-Hamstring-Heben"),
    ("Bridge", "Brücke"),
    ("Plank", "Planke"),
    ("Side Plank", "Seitenplanke"),
    ("Crunch", "Crunch"),
    ("Sit-Up", "Sit-Up"),
    ("Sit Up", "Sit-Up"),
    ("Leg Raise", "Beinheben"),
    ("Knee Raise", "Knieheben"),
    ("Toe Touch", "Zehenberühren"),
    ("Russian Twist", "Russischer Twist"),
    ("Oblique", "Schräger Bauchmuskel"),
    ("Ab Wheel", "Bauchmuskelrad"),
    ("Ab Roller", "Bauchradtrainer"),
    ("Ab Crunch", "Bauchcrunch"),
    ("Windmill", "Windmühle"),
    ("Turkish Get-Up", "Türkisches Aufstehen"),
    ("Snatch", "Reißen"),
    ("Clean and Jerk", "Stoßen und Reißen"),
    ("Power Clean", "Power-Stoßen"),
    ("Hang Clean", "Hang-Stoßen"),
    ("Clean", "Stoßen"),
    ("Jerk", "Ausstoßen"),
    ("Push Press", "Push-Press"),
    ("Push Jerk", "Push-Jerk"),
    ("Power Snatch", "Power-Reißen"),
    ("Hang Snatch", "Hang-Reißen"),
    ("Swing", "Schwingen"),
    ("Thruster", "Thruster"),
    ("Farmer Walk", "Farmergehen"),
    ("Farmer's Walk", "Farmergehen"),
    ("Carry", "Tragen"),
    ("Drag", "Ziehen"),
    ("Flip", "Umwerfen"),
    ("Tire Flip", "Reifenumwerfen"),
    ("Sled Push", "Schlittenschieben"),
    ("Sled Pull", "Schlittenziehen"),
    ("Sled Drag", "Schlittenziehen"),
    ("Battle Rope", "Battle-Rope"),
    ("Box Jump", "Box-Sprung"),
    ("Broad Jump", "Weitsprung"),
    ("Depth Jump", "Tiefsprung"),
    ("Jump Squat", "Sprung-Kniebeuge"),
    ("Jump", "Sprung"),
    ("Bound", "Sprung"),
    ("Hop", "Hüpfen"),
    ("Skip", "Seilspringen"),
    ("Sprint", "Sprint"),
    ("Jog", "Joggen"),
    ("Run", "Laufen"),
    ("Walk", "Gehen"),
    ("Step-Up", "Aufsteigen"),
    ("Step Up", "Aufsteigen"),
    ("Burpee", "Burpee"),
    ("Mountain Climber", "Bergsteiger"),
    ("Bear Crawl", "Bärengang"),
    ("Inchworm", "Raupengang"),
    ("Rollout", "Ausrollen"),
    ("Dragon Flag", "Drachenflagge"),
    ("Hollow Body", "Hohlkörperhaltung"),
    ("L-Sit", "L-Sitz"),
    ("Handstand", "Handstand"),
    ("Muscle-Up", "Muscle-Up"),
    ("Dumbbell Swing", "Kurzhantel-Schwingen"),
    ("Kettlebell Swing", "Kettlebell-Schwingen"),
    ("Hip Circle", "Hüftkreisen"),
    ("Arm Circle", "Armkreisen"),
    ("Ankle Circle", "Knöchelkreisen"),
    ("Neck Circle", "Nackenkreisen"),
    ("Stretch", "Dehnung"),
    ("SMR", "SMR"),
    ("Foam Rolling", "Schaumstoffrollen"),
    ("Massage", "Massage"),
    ("Hip Flexor Stretch", "Hüftbeuger-Dehnung"),
    # ── Positions / modifiers ─────────────────────────────────────────────────
    ("Alternating", "Alternierend"),
    ("Alternate", "Alternierend"),
    ("Single-Arm", "Einarmig"),
    ("Single Arm", "Einarmig"),
    ("One-Arm", "Einarmig"),
    ("One Arm", "Einarmig"),
    ("Two-Arm", "Beidarmig"),
    ("Two Arm", "Beidarmig"),
    ("Double", "Doppelt"),
    ("Incline", "Schrägbank"),
    ("Decline", "Negativbank"),
    ("Flat", "Flachbank"),
    ("Seated", "Sitzend"),
    ("Standing", "Stehend"),
    ("Lying", "Liegend"),
    ("Supine", "Rückenlage"),
    ("Prone", "Bauchlage"),
    ("Kneeling", "Kniend"),
    ("Bent-Over", "Vorgebeugt"),
    ("Bent Over", "Vorgebeugt"),
    ("Upright", "Aufrecht"),
    ("Overhead", "Überkopf"),
    ("Behind Neck", "Im Nacken"),
    ("Behind-Neck", "Im Nacken"),
    ("Wide Grip", "Weiter Griff"),
    ("Wide-Grip", "Weiter Griff"),
    ("Close Grip", "Enger Griff"),
    ("Close-Grip", "Enger Griff"),
    ("Narrow Grip", "Enger Griff"),
    ("Overhand", "Obergriff"),
    ("Underhand", "Untergriff"),
    ("Neutral Grip", "Neutralgriff"),
    ("Supinated", "Supiniert"),
    ("Pronated", "Proniert"),
    ("Reverse", "Umgekehrt"),
    ("Cross", "Überkreuz"),
    ("Lateral", "Seitlich"),
    ("Diagonal", "Diagonal"),
    ("Vertical", "Vertikal"),
    ("Horizontal", "Horizontal"),
    ("Inner", "Innen"),
    ("Outer", "Außen"),
    ("Upper", "Oberer"),
    ("Lower", "Unterer"),
    ("Full", "Komplett"),
    ("Half", "Halb"),
    ("Partial", "Teilweise"),
    ("Pause", "Pause"),
    ("Tempo", "Tempo"),
    ("Explosive", "Explosiv"),
    ("Slow", "Langsam"),
    ("Controlled", "Kontrolliert"),
    ("Assisted", "Unterstützt"),
    ("Weighted", "Gewichtet"),
    ("Bodyweight", "Körpergewicht"),
    ("Unilateral", "Einseitig"),
    ("Bilateral", "Beidseitig"),
    ("Advanced", "Fortgeschritten"),
    ("Beginner", "Anfänger"),
    ("Anterior", "Vorderer"),
    ("Posterior", "Hinterer"),
    ("Medial", "Medialer"),
    ("Sumo", "Sumo"),
    ("Conventional", "Konventionell"),
    ("Pendulum", "Pendel"),
    ("Around The World", "Um die Welt"),
    ("Around The Worlds", "Um die Welt"),
    # ── Body parts ────────────────────────────────────────────────────────────
    ("Chest", "Brust"),
    ("Back", "Rücken"),
    ("Shoulders", "Schultern"),
    ("Shoulder", "Schulter"),
    ("Deltoid", "Deltamuskel"),
    ("Bicep", "Bizeps"),
    ("Biceps", "Bizeps"),
    ("Tricep", "Trizeps"),
    ("Triceps", "Trizeps"),
    ("Forearm", "Unterarm"),
    ("Forearms", "Unterarme"),
    ("Wrist", "Handgelenk"),
    ("Trapezius", "Trapezmuskel"),
    ("Traps", "Trapezmuskel"),
    ("Lats", "Latissimus"),
    ("Lat", "Lat"),
    ("Rhomboid", "Rhomboid"),
    ("Serratus", "Serratus"),
    ("Pectoral", "Brustmuskel"),
    ("Pectorals", "Brustmuskeln"),
    ("Core", "Rumpf"),
    ("Abdominal", "Bauch"),
    ("Abdominals", "Bauch"),
    ("Abs", "Bauch"),
    ("Oblique", "Schrägbauch"),
    ("Obliques", "Schrägbauch"),
    ("Lower Back", "Unterer Rücken"),
    ("Upper Back", "Oberer Rücken"),
    ("Mid Back", "Mittlerer Rücken"),
    ("Spinal", "Wirbelsäule"),
    ("Erector", "Rückenstrecker"),
    ("Hip", "Hüfte"),
    ("Hips", "Hüften"),
    ("Glute", "Gesäß"),
    ("Glutes", "Gesäß"),
    ("Buttocks", "Gesäß"),
    ("Quad", "Quadrizeps"),
    ("Quads", "Quadrizeps"),
    ("Quadriceps", "Quadrizeps"),
    ("Hamstring", "Oberschenkelrückseite"),
    ("Hamstrings", "Oberschenkelrückseite"),
    ("Adductor", "Adduktoren"),
    ("Adductors", "Adduktoren"),
    ("Abductor", "Abduktoren"),
    ("Abductors", "Abduktoren"),
    ("Groin", "Leiste"),
    ("Calf", "Wade"),
    ("Calves", "Waden"),
    ("Tibialis", "Schienbeinmuskel"),
    ("Shin", "Schienbein"),
    ("Ankle", "Knöchel"),
    ("Knee", "Knie"),
    ("Thigh", "Oberschenkel"),
    ("Inner Thigh", "Innerer Oberschenkel"),
    ("Neck", "Nacken"),
    ("Head", "Kopf"),
    ("Spine", "Wirbelsäule"),
    # ── Common qualifiers ─────────────────────────────────────────────────────
    ("With Bands", "mit Band"),
    ("With Band", "mit Band"),
    ("On Ball", "auf Ball"),
    ("On Bench", "auf Bank"),
    ("On Floor", "auf dem Boden"),
    ("On Box", "auf Box"),
    ("From Floor", "vom Boden"),
    ("Off Floor", "vom Boden"),
    ("Floor", "Boden"),
    ("Wall", "Wand"),
    ("Box", "Box"),
    ("Ball", "Ball"),
    ("Chair", "Stuhl"),
    ("Door", "Tür"),
    ("Table", "Tisch"),
    ("Bar", "Stange"),
    ("Rack", "Ständer"),
    ("Frog", "Frosch"),
    ("Dragon", "Drachen"),
    ("Donkey", "Esel"),
    ("Spider", "Spinne"),
    ("Gorilla", "Gorilla"),
    ("Bear", "Bär"),
    ("Crab", "Krabbe"),
    ("Cat", "Katze"),
    ("Cobra", "Kobra"),
    ("Pigeon", "Taube"),
    ("Butterfly", "Schmetterling"),
    ("Air", "Luft"),
    ("Jumbo", "Groß"),
    ("Mini", "Mini"),
    ("Anti-Gravity", "Anti-Schwerkraft"),
    ("Isometric", "Isometrisch"),
    ("Plyometric", "Plyometrisch"),
]

# Manual overrides for exercises with non-literal names
MANUAL_OVERRIDES = {
    "3/4 Sit-Up": "Dreiviertel Sit-Up",
    "90/90 Hamstring": "90/90 Oberschenkelrückseite-Dehnung",
    "Ab Roller": "Bauchradtrainer",
    "Ab Crunch Machine": "Bauchcrunch-Maschine",
    "Air Bike": "Air-Bike",
    "All Fours Quad Stretch": "Quadrizepsdehnung im Vierfüßlerstand",
    "Anterior Tibialis-SMR": "Vorderer Schienbeinmuskel SMR",
    "Arnold Dumbbell Press": "Arnold-Schulterdrücken",
    "Atlas Stone Trainer": "Atlas-Stein-Trainer",
    "Atlas Stones": "Atlas-Steine",
    "Backward Drag": "Rückwärtiges Schlittenziehen",
    "Backward Medicine Ball Throw": "Rückwärtiger Medizinballwurf",
    "Ball Leg Curl": "Beincurl auf dem Ball",
    "Band Assisted Pull-Up": "Klimmzug mit Bandunterstützung",
    "Band Good Morning": "Good Morning mit Band",
    "Band Good Morning (Pull Through)": "Good Morning mit Band (Durchzug)",
    "Band Hip Adductions": "Hüftadduktion mit Band",
    "Band Pull Apart": "Bandauseinanderziehen",
    "Barbell Ab Rollout": "Langhantel-Bauchausrollen",
    "Barbell Curl": "Langhantel-Curl",
    "Barbell Full Squat": "Volle Langhantel-Kniebeuge",
    "Barbell Glute Bridge": "Langhantel-Gesäßbrücke",
    "Barbell Good Morning": "Langhantel Good Morning",
    "Barbell Ground and Pound": "Langhantel Ground and Pound",
    "Barbell Hip Thrust": "Langhantel-Hüftstrecken",
    "Barbell Rollout": "Langhantel-Ausrollen",
    "Barbell Shoulder Press": "Langhantel-Schulterdrücken",
    "Barbell Side Split Squat": "Langhantel-Seitkniebeuge",
    "Barbell Walking Lunge": "Langhantel-Ausfallschritte",
    "Behind The Back Barbell Shrug": "Langhantel-Schulterziehen hinter dem Rücken",
    "Bench Dip": "Bank-Dip",
    "Bent-Knee Hip Raise": "Hüftheben mit gebeugten Knien",
    "Board Press": "Board Press",
    "Body Tricep Press": "Körpergewicht-Trizepsdrücken",
    "Body-Up": "Body-Up",
    "Bodyweight Squat": "Körpergewicht-Kniebeuge",
    "Bosu Ball Cable Crunch with Side Bend": "Bosu-Ball Kabel-Crunch mit Seitbeuge",
    "Bottoms-Up Clean From The Hang Position": "Bottoms-Up Stoßen aus der Hängeposition",
    "Box Skip": "Box-Sprung",
    "Butt Kicks": "Fersenschläge",
    "Butterfly": "Schmetterling",
    "Cable Crunch": "Kabelzug-Crunch",
    "Cable Crossover": "Kabelzugkreuzung",
    "Cable Glute Kickback": "Kabelzug-Gesäß-Kickback",
    "Cable Hip Adduction": "Kabelzug-Hüftadduktion",
    "Cable Kneeling Crunch": "Kabelzug-Crunch kniend",
    "Cable Lying Triceps Extension": "Kabelzug-Trizepsstreckung liegend",
    "Cable Overhead Triceps Extension": "Kabelzug-Trizepsstreckung Überkopf",
    "Cable Pull Through": "Kabelzug-Durchzug",
    "Cable Rear Delt Fly": "Kabelzug-Deltaheben hinten",
    "Cable Rope Overhead Tricep Extension": "Kabelzug-Seil-Trizepsstreckung Überkopf",
    "Cable Rope Rear-Delt Rows": "Kabelzug-Seil-Rudern hinten",
    "Cable Seated Shoulder Internal Rotation": "Kabelzug-Schulterinnenrotation sitzend",
    "Cable Shrug": "Kabelzug-Schulterziehen",
    "Cable Standing Rear Delt Row with Rope": "Kabelzug-Rudern hinten stehend mit Seil",
    "Cable Wrist Curl": "Kabelzug-Handgelenk-Curl",
    "Calf-Machine Donkey Calf Raise": "Maschinen-Esel-Wadenlifte",
    "Calf Raise - Seated": "Wadenlifte sitzend",
    "Clean and Press": "Stoßen und Drücken",
    "Clean Deadlift": "Stoßen-Kreuzheben",
    "Clapping Pushup": "Klatsch-Liegestütz",
    "Close-Grip Front Lat Pulldown": "Latzug eng vorne",
    "Close-Grip EZ-Bar Press": "EZ-Stange Drücken eng",
    "Close-Grip Barbell Bench Press": "Langhantel-Bankdrücken eng",
    "Decline Barbell Bench Press": "Negativbank Langhantel-Bankdrücken",
    "Decline Barbell Pullover": "Negativbank Langhantel-Überzug",
    "Decline Crunch": "Negative Crunches",
    "Decline Dumbbell Bench Press": "Negativbank Kurzhantel-Bankdrücken",
    "Deficit Deadlift": "Deficit Kreuzheben",
    "Diamond Pushup": "Diamant-Liegestütz",
    "Donkey Calf Raises": "Esel-Wadenlifte",
    "Donkey Kicks": "Eseltritts",
    "Dumbbell Bench Press": "Kurzhantel-Bankdrücken",
    "Dumbbell Bicep Curl": "Kurzhantel-Bizepscurl",
    "Dumbbell Box Squat": "Kurzhantel-Box-Kniebeuge",
    "Dumbbell Deadlift": "Kurzhantel-Kreuzheben",
    "Dumbbell Flyes": "Kurzhantel-Fliegender",
    "Dumbbell Front Raise": "Kurzhantel-Frontheben",
    "Dumbbell Incline Fly": "Kurzhantel-Schrägbank Fliegender",
    "Dumbbell Kickback": "Kurzhantel-Kickback",
    "Dumbbell Lateral Raise": "Kurzhantel-Seitheben",
    "Dumbbell Lunges": "Kurzhantel-Ausfallschritte",
    "Dumbbell Rear Delt Row": "Kurzhantel-Rudern hinten",
    "Dumbbell Romanian Deadlift": "Kurzhantel-Rumänisches Kreuzheben",
    "Dumbbell Scaption": "Kurzhantel-Scaption",
    "Dumbbell Seated Box Jump": "Kurzhantel-Box-Sprung sitzend",
    "Dumbbell Shoulder Press": "Kurzhantel-Schulterdrücken",
    "Dumbbell Shrug": "Kurzhantel-Schulterziehen",
    "Dumbbell Squat": "Kurzhantel-Kniebeuge",
    "Dumbbell Step Ups": "Kurzhantel-Aufsteigen",
    "Dumbbell Tricep Extension": "Kurzhantel-Trizepsstreckung",
    "Elevated Cable Rows": "Erhöhtes Kabelzugrudern",
    "Face Pull": "Gesichtszug",
    "Flat Bench Cable Flyes": "Flachbank Kabelzug Fliegender",
    "Flat Dumbbell Flyes": "Flachbank Kurzhantel Fliegender",
    "Floor Press": "Bodendrücken",
    "Flutter Kicks": "Fußschläge",
    "Frog Sit-Ups": "Frosch Sit-Ups",
    "Front Box Jump": "Vorderer Box-Sprung",
    "Goblet Squat": "Goblet-Kniebeuge",
    "Hang Snatch - Below The Knee": "Hang-Reißen unter dem Knie",
    "High Knees": "Knieheben",
    "Hip Adductor": "Hüftadduktor",
    "Hip Circle": "Hüftkreisen",
    "Inchworm": "Raupengang",
    "Inverted Row": "Umgekehrtes Rudern",
    "Iron Cross": "Eisernes Kreuz",
    "Jefferson Squat": "Jefferson-Kniebeuge",
    "Jump Rope": "Seilspringen",
    "Jumping Jacks": "Hampelmänner",
    "Jumping Jack": "Hampelmann",
    "Kip Up": "Kip-Hochkommen",
    "Kipping Muscle Up": "Kipping Muscle-Up",
    "Knee Push-Up": "Knie-Liegestütz",
    "Landmine": "Landmine",
    "Leg-Up Hamstring Stretch": "Hamstring-Dehnung mit Beinanheben",
    "Man Makers": "Man Makers",
    "Medicine Ball Chest Pass": "Medizinball-Brustpass",
    "Medicine Ball Slam": "Medizinball-Schlag",
    "Mountain Climber": "Bergsteiger",
    "Muscle Snatch": "Muskelreißen",
    "Oblique Crunches": "Schrägbauch-Crunches",
    "One-Legged Cable Kickback": "Einbeiniger Kabelzug-Kickback",
    "Pallof Press": "Pallof-Press",
    "Pause Squat": "Pause-Kniebeuge",
    "Pigeon Stretch": "Tauben-Dehnung",
    "Pin Squat": "Pin-Kniebeuge",
    "Plank": "Planke",
    "Power Clean from Blocks": "Power-Stoßen von Blöcken",
    "Power Jerk": "Power-Jerk",
    "Rack Pull": "Rack-Kreuzheben",
    "Rack Pulls with Bands": "Rack-Kreuzheben mit Band",
    "Renegade Row": "Renegade-Rudern",
    "Romanian Deadlift": "Rumänisches Kreuzheben",
    "Rope Crunch": "Seil-Crunch",
    "Russian Twist": "Russischer Twist",
    "Safety Squat Bar Squat": "Safety-Squat-Bar-Kniebeuge",
    "Scapular Pull-Up": "Schulterblatt-Klimmzug",
    "Seated Barbell Behind Head Military Press": "Militärdrücken hinter dem Kopf sitzend",
    "Seated Barbell Military Press": "Militärdrücken sitzend",
    "Seated Calf Raise": "Wadenlifte sitzend",
    "Side Lateral Raise": "Seitliches Seitheben",
    "Single-Leg Press": "Einbeinige Beinpresse",
    "Sissy Squat": "Sissy-Kniebeuge",
    "Ski Jumps": "Skisprünge",
    "Sled Drag": "Schlittenziehen",
    "Sliding Leg Curl": "Gleitschieber-Beincurl",
    "Snatch Balance": "Reißen Balance",
    "Snatch Deadlift": "Reißen-Kreuzheben",
    "Snatch Pull": "Reißen-Zug",
    "Snatch Shrug": "Reißen-Schulterziehen",
    "Split Squat": "Ausfallschritte",
    "Stability Ball Crunch": "Stabilityball-Crunch",
    "Stability Ball Plank": "Stabilityball-Planke",
    "Standing Cable Chest Press": "Kabelzug-Brustdrücken stehend",
    "Standing Leg Curl": "Beincurl stehend",
    "Star Jump": "Sternensprung",
    "Stiff-Legged Dumbbell Deadlift": "Kurzhantel-Kreuzheben mit gestreckten Beinen",
    "Sumo Deadlift": "Sumo-Kreuzheben",
    "Superman": "Superman",
    "Tate Press": "Tate-Press",
    "Tire Flip": "Reifenumwerfen",
    "Tire Kick": "Reifentritt",
    "Trap Bar Deadlift": "Trap-Stangen-Kreuzheben",
    "Tricep Pushdown": "Trizepsdrücken",
    "Two-Arm Dumbbell Preacher Curl": "Beidarmiger Kurzhantel-Preacher-Curl",
    "Underhand Cable Pulldown": "Untergriff-Latzug",
    "Upright Row": "Aufrechtes Rudern",
    "V-Bar Pulldown": "V-Stangen-Latzug",
    "V-Up": "V-Aufrichten",
    "Walking Lunge": "Ausfallschritte gehend",
    "Weighted Ball Hyperextension": "Gewichteter Ball-Rückenstreckung",
    "Wide-Grip Barbell Bench Press": "Langhantel-Bankdrücken weiter Griff",
    "Wide-Grip Barbell Curl": "Langhantel-Curl weiter Griff",
    "Wide-Grip Rear Pull-Up": "Klimmzug weiter Griff hinten",
    "Wipers": "Scheibenwischer",
    "Wrist Roller": "Handgelenk-Roller",
    "Yates Row": "Yates-Rudern",
    "Zercher Good Morning": "Zercher Good Morning",
    "Zercher Squat": "Zercher-Kniebeuge",
}

# ── Translation logic ─────────────────────────────────────────────────────────

def translate_name(name: str) -> str:
    if name in MANUAL_OVERRIDES:
        return MANUAL_OVERRIDES[name]

    result = name
    # Apply phrase map in order (longest first already, but also sort by len desc)
    for eng, de in PHRASE_MAP:
        # Whole-word / phrase replacement, case-insensitive
        pattern = r'(?<![A-Za-z])' + re.escape(eng) + r'(?![A-Za-z])'
        result = re.sub(pattern, de, result, flags=re.IGNORECASE)

    return result


def translate_description(desc: str) -> str | None:
    """
    Build a brief German description from key terms in the English text.
    For most exercises a template based on the translated name is good enough.
    """
    if not desc:
        return None
    # Keep it short — just note it's an exercise and translate main nouns
    result = desc
    for eng, de in PHRASE_MAP:
        pattern = r'(?<![A-Za-z])' + re.escape(eng) + r'(?![A-Za-z])'
        result = re.sub(pattern, de, result, flags=re.IGNORECASE)
    # Trim to a reasonable length
    if len(result) > 300:
        result = result[:300].rsplit(' ', 1)[0] + '...'
    return result


# ── Helpers ──────────────────────────────────────────────────────────────────

def parse_json_list(raw: str) -> list:
    try:
        r = json.loads(raw)
        return r if isinstance(r, list) else []
    except Exception:
        return []

def build_description(instructions_raw: str) -> str:
    steps = parse_json_list(instructions_raw)
    if not steps:
        return ''
    text = ' '.join(str(s).strip() for s in steps)
    return text[:400].rsplit(' ', 1)[0] + '...' if len(text) > 400 else text


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root = os.path.join(script_dir, '..')
    csv_path   = os.path.join(root, 'exercises', 'exercises.csv')
    cache_path = os.path.join(script_dir, 'translations_de.json')

    with open(csv_path, newline='', encoding='utf-8') as f:
        rows = list(csv.DictReader(f.read().lstrip('\n').splitlines()))

    cache: dict = {}
    if os.path.exists(cache_path):
        with open(cache_path, encoding='utf-8') as f:
            cache = json.load(f)

    added = 0
    for row in rows:
        name = row['name'].strip()
        if name in cache:
            continue
        desc_en = build_description(row.get('instructions', '[]'))
        name_de = translate_name(name)
        desc_de = translate_description(desc_en)
        cache[name] = {'nameDe': name_de, 'descriptionDe': desc_de}
        added += 1

    with open(cache_path, 'w', encoding='utf-8') as f:
        json.dump(cache, f, ensure_ascii=False, indent=2)

    print(f'Translated {added} new exercises. Total cache: {len(cache)}.')
    print(f'Output: {cache_path}')
    print('Now run: python3 tool/generate_seeds.py')
