// Conditional export: the native implementation (`open_filex` on
// Android/iOS, `url_launcher` + `Uri.file` on Windows/macOS/Linux) where
// `dart:io` exists, the web implementation (a blob-URL download) where it
// doesn't, and a stub everywhere neither condition holds. Same pattern as
// `chat_attachment_file.dart` and `video_blob_url.dart`, and the same
// non-negotiable reason: `dart:io` and `open_filex` cannot be *imported at
// all* in code compiled for web, so a `kIsWeb` branch inside one file
// cannot substitute for this. See docs/chat-attachments.md §17.
//
// Every implementation exports one function:
//
//   Future<AttachmentOpenOutcome> openAttachmentExternally({
//     required Uint8List bytes,
//     required String name,   // ChatAttachmentRef.name — peer-controlled
//     required String mime,
//     required String id,     // ChatAttachmentRef.id — also peer-controlled
//   })
//
// [name] and [id] are both client-generated by whoever *sent* the message.
// Every implementation sanitises them via `safeAttachmentFileName` before
// either reaches a filesystem path or a browser's `download` attribute —
// never sanitise at the call site and pass the result in, so there is
// exactly one place per platform that does it, not a convention a caller
// has to remember.
export 'attachment_opener_stub.dart'
    if (dart.library.io) 'attachment_opener_io.dart'
    if (dart.library.js_interop) 'attachment_opener_web.dart';

import 'dart:typed_data';

import 'package:ForgeForm/feature/chat/domain/attachment_open_outcome.dart';

/// The shape every `openAttachmentExternally` implementation above has —
/// named here so a caller wanting to override it (a test, in this codebase)
/// has a type to declare a field or parameter with, rather than repeating
/// the signature at every call site.
typedef OpenAttachmentExternally =
    Future<AttachmentOpenOutcome> Function({
      required Uint8List bytes,
      required String name,
      required String mime,
      required String id,
    });
